force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <label>Exchange Order</label>
    <nameField>
        <label>Exchange Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Side__c.field-meta.xml
<CustomField>
    <fullName>Order_Side__c</fullName>
    <label>Order Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market</fullName>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Security__c.field-meta.xml
<CustomField>
    <fullName>Security__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Security</label>
    <referenceTo>Security__c</referenceTo>
    <relationshipLabel>Exchange Orders</relationshipLabel>
    <relationshipName>Exchange_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/Exchange_Order_Match__c.object-meta.xml
<CustomObject>
    <label>Exchange Order Match</label>
    <nameField>
        <label>Exchange Order Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Order Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ExchangeOrderHandlerTest.cls
@isTest
public  class ExchangeOrderHandlerTest {
   
    @TestSetup
    static void makeData(){
        //Create Security
        List<Security__c> securitiesToInsert = new List<Security__c>();
        securitiesToInsert.add(new Security__c(Symbol__c='TSLA'));
        securitiesToInsert.add(new Security__c(Symbol__c='AMZN'));
        insert securitiesToInsert;

        List<Exchange_Order__c> testOrders = new List<Exchange_Order__c>();
        testOrders.add(new Exchange_Order__c(Order_Side__c = 'Buy',  Quantity__c = 10, Price__c = 10, Security__c = securitiesToInsert[0].Id, Status__c = 'Open', Order_Type__c = 'Market'));
        testOrders.add(new Exchange_Order__c(Order_Side__c = 'Sell',  Quantity__c = 10, Price__c = 9, Security__c =  securitiesToInsert[0].Id, Status__c = 'Open', Order_Type__c = 'Limit'));
        testOrders.add(new Exchange_Order__c(Order_Side__c = 'Buy',  Quantity__c = 10, Price__c = 15, Security__c =  securitiesToInsert[1].Id, Status__c = 'Open', Order_Type__c = 'Market'));
        testOrders.add(new Exchange_Order__c(Order_Side__c = 'Sell',  Quantity__c = 10, Price__c = 8, Security__c =  securitiesToInsert[1].Id, Status__c = 'Open', Order_Type__c = 'Limit'));
        insert testOrders;


    }

    @isTest
    private static void testOrderMatching() {
       
        Test.startTest();
            ExchangeOrderHandler.manageOrder();
        Test.stopTest();

         // Verify that the matched orders have been created
         List<Exchange_Order_Match__c> matchedOrders = [SELECT Id,Quantity__c,Price__c FROM Exchange_Order_Match__c];
         System.assertEquals(2, matchedOrders.size());
 
         // Verify that the matched order has the correct values
         Exchange_Order_Match__c matchedOrder = matchedOrders[0];
         System.assertEquals(10, matchedOrder.Quantity__c);
         System.assertEquals(9, matchedOrder.Price__c);
 
         // Verify that the matched orders have been updated to 'Completed'
         List<Exchange_Order__c> completedOrders = [SELECT Id, Status__c FROM Exchange_Order__c WHERE Status__c = 'Filled'];
         System.assertEquals(4, completedOrders.size());
        
    }
    
}