force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <label>Exchange Order</label>
    <nameField>
        <label>Exchange Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Side__c.field-meta.xml
<CustomField>
    <fullName>Order_Side__c</fullName>
    <label>Order Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market</fullName>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Security__c.field-meta.xml
<CustomField>
    <fullName>Security__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Security</label>
    <referenceTo>Security__c</referenceTo>
    <relationshipLabel>Exchange Orders</relationshipLabel>
    <relationshipName>Exchange_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExchangeOrderDataAccessor.cls
public class ExchangeOrderDataAccessor {
    
	 public static List<Security__c> getSecurity() {
        return [SELECT ID,Symbol__c FROM Security__c];
    }

    public static Security getSecurityBySymbol(String Symbol){
        return [Select Id,Symbol__c from Security__c where Symbol__c=:Symbol];
    }

    public static List<Exchange_Order__c> getOder(String orderId) {
        return [SELECT Id,Order_Side__c,Order_Total__c , Quantity__c, Price__c, Security__c ,Status__c, Order_Type__c  FROM Exchange_Order__c WHERE Id =: orderId];
    }
}