force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <label>Exchange Order</label>
    <nameField>
        <label>Exchange Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Side__c.field-meta.xml
<CustomField>
    <fullName>Order_Side__c</fullName>
    <label>Order Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market</fullName>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Security__c.field-meta.xml
<CustomField>
    <fullName>Security__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Security</label>
    <referenceTo>Security__c</referenceTo>
    <relationshipLabel>Exchange Orders</relationshipLabel>
    <relationshipName>Exchange_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExchangeOrderService.cls
@RestResource(urlMapping='/order/*')
Global class ExchangeOrderService {
	
        @HttpGet
        global static void doGet() {
            RestRequest req = RestContext.request;
            RestResponse res = RestContext.response;
            String requestType = req.params.get('requestType');
            res.headers.put('Content-Type','application/json');

            switch on requestType{
                when 'securities'{
                    res.responseBody = Blob.valueOf(JSON.serialize(ExchangeOrderDataAccessor.getSecurity())); 
                }
                when 'order' {
                    String orderId = req.params.get('orderId');
                    res.responseBody = Blob.valueOf(JSON.serialize(ExchangeOrderDataAccessor.getOder(orderId)));
                }
            }

            if(res.responseBody!=null){
                res.statusCode = 200;
            }else{
                res.statusCode = 500;
                res.responseBody = Blob.valueOf('Could not find any records matching the criteria.');
            }
        }
    
        @HttpPost
        global static void createOrUpdateOrder() {
            RestRequest req = RestContext.request;
            RestResponse res = RestContext.response;
            res.headers.put('Content-Type','application/json');
            Blob body = req.requestBody;
            String bodyStr = body.toString();
            OrderWrapper order = (OrderWrapper)JSON.deserialize(bodyStr, OrderWrapper.class);
            
            try{
                upsert constructOrder(order);
                res.statusCode = 200;
            }catch(Exception e){
                res.statusCode = 500;
            }
        }

      
        public static Exchange_Order__c constructOrder(OrderWrapper orderWrapper){
            Exchange_Order__c order = new Exchange_Order__c(
                Order_Side__c = orderWrapper.orderSide,  
                Quantity__c = orderWrapper.quantity, 
                Price__c = orderWrapper.price, 
                Security__c = ExchangeOrderDataAccessor.getSecurityBySymbol(orderWrapper.symbol).Id, 
                Order_Type__c = orderWrapper.orderType
            );

            if(orderWrapper.orderId!=null){
                order.Id = orderWrapper.orderId;
            }

            if(orderWrapper.orderStatus!=null){
                order.Status__c = orderWrapper.orderStatus;
            }
            return order;
        }
    
}